name: Hooks Actions
run-name: Action is going ON
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      steps:
        - use: actions/checkout@v3
        - use: actions/setup-node@v3
          with:
        - name: Your react hooks ready to go
          run: |
              echo "This is workflow for checking github actions"
